## Numpy Arrays

#### Concepts covered

1. .ones()
2. .zeros()
3. .linspace()
4. .eye()
5. .random.*()
6. .arange()
7. .array()

In [1]:
import numpy as np

In [37]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [38]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.linspace(0,100,50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand(1)

array([0.88556331])

In [11]:
np.random.rand(4,5)

array([[0.79121839, 0.38456769, 0.75225167, 0.35402409, 0.59204367],
       [0.18596272, 0.4443401 , 0.57742527, 0.89097917, 0.46682329],
       [0.65366423, 0.42924723, 0.98762563, 0.46384959, 0.41042627],
       [0.45063829, 0.84634433, 0.40698872, 0.08468589, 0.56932298]])

In [13]:
np.random.randn(5,5)

array([[-0.68793733,  0.52713606,  0.59260422, -0.71008616, -0.90372358],
       [ 0.41458423,  0.87811722,  0.81314745,  1.27746278,  0.77288807],
       [-1.10190161, -0.72904541, -1.35498572,  0.06651923, -0.65590628],
       [-0.29816936, -0.68279014,  0.11308848,  1.57519647,  0.28192796],
       [-0.75376263,  0.79215714, -0.06132922,  1.17515799,  0.08833654]])

In [17]:
np.random.randint(5,100,5)

array([ 9, 44, 36, 13, 65])

In [18]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr

array([12, 21, 29,  2, 41, 19,  8, 18, 43, 13])

In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
arr.shape

(25,)

In [23]:
arr.reshape(5,5).shape

(5, 5)

In [25]:
arr.dtype

dtype('int64')

In [26]:
ranarr

array([12, 21, 29,  2, 41, 19,  8, 18, 43, 13])

In [27]:
ranarr.max()

43

#### argmax returns the index of the max number

In [28]:
ranarr.argmax()

8

## Numpy Operations

mathematical operations can be applied to numpy arrays just as they can be numbers. the operand will be applied between the same indexes of the array.

In [30]:
arr = np.arange(1,10)

In [31]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [34]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
arr ** 3

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [36]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109])

In [39]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [40]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [41]:
np.max(arr)

9

In [42]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [43]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Numpy Indexing and Selection

In [44]:
arr = np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[6]

6

In [47]:
arr[1:5]

array([1, 2, 3, 4])

In [48]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [49]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### broadcasting an array is a numpy specific function. this can set multiple indexes to the same value as shown below

In [51]:
arr[0:5] = 100

In [52]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
arr = np.arange(0,11)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
slice_of_arr = arr[0:6]

In [56]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [57]:
slice_of_arr[:] = 99

In [58]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [59]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy = arr.copy()

In [61]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr_copy[:] = 299

In [63]:
arr_copy

array([299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299])

In [64]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [65]:
#mat[row, column]
#mat[row][column]

In [66]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [68]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
mat[0]

array([ 5, 10, 15])

In [70]:
mat[2]

array([35, 40, 45])

In [71]:
mat[1,2]

30